### PR TITLE
z-index foundations for simple z-index and google's Material design Elevations

### PR DESCRIPTION
**Pull request by area73**
I think it will be nice if you include a foundation for z-index.
In many projets wen you are dealing with z-index, specialy  for mobile view, you need to know were to put your layers in your display view (z-index)

### CODE REVIEW

**Comment by danifornells** [comment]
Thanks @area73,
we're completely agree on having z-indexes on foundations, but after checking your PR, I believe that we need to find the proper naming for that. You've currently used the MD names, what are really coupled with components or material names. The foundations layer should be agnostic of the bottom layers, so is better to use abstract names for them. We will try to figure out a good ones, but if you have any proposal, will be welcome.

Some examples could be:
- Flat, Raised, Levitated, Overfly
- Ground, Troposphere, Stratosphere, Mesosphere 
- Basement, Ground, Mezzanine, Floor-1, Attic, Roof

**Comment by area73** [comment]
ok, I added two arrays one for material design because I though it could be an standard because the names that they are using are generic. 
But I also provide a simple array with these names:
base": "offcanvas":   "dropdown":   "tooltip":   "lightbox":  
That may be more apropiate for this foundation

**Comment by jyulzz** [comment]
Hey everyone,

I see 3 naming levels here : 

- Material Design-compliant names : $f-z-index--md-menu
- By-destination names : $f-z-index-dropdown
- By Z-index level names : Ground, Troposphere, Stratosphere, Mesosphere...

To be consistent with the naming schemes of other foundations, I would first define Z-index level names in simple terms, such as level names : 
_Level 5, Level 4, Level 3, Level 2, Level 1, Level 0, Level -1, Level -2, Level -3, Level -4, Level -5_ 
or heights :
_Highest, Higher, High, Flat, Low, Lower, Lowest_.
The atmospheric layer names are interesting but most people will have difficulty in placing them relative to each other, and reading/spelling the names might be an issue too.

I would then use these variables in by-destination names or MD-compliant names.

**Comment by area73** [comment]
Vamos cerrando temitas 😂

**Pull request closed without merging**
